### ISSUE TITLE
Safari back button

### ISSUE THREAD

**Issue by ghost** [michael-bateman/projects.michaelbateman.ca#2]
Please answer the following:

a) How you found the bug
using your website

b) Where you found the bug (ex. homepage)
your whole site

c) If this issue happens multiple times
yes - always

d) Anything else that would be useful to know
I went to your site to find that the back button on Safari does not work.  It just refreshes the page.  Please fix, ASAP

**Comment by michael-bateman** [comment]
Hi @gafetest ,

Thank you for your feedback.  I've tried the issue in Safari and it's a bug, but in Firefox and IE everything is ok.  I would think this is a bug in "Safari" but I am trying to see if resetting DNS will work.

I'll let you know when a fix has been made available.

## Update

Resetting the DNS settings did not work.  I am looking into a fix for this

**Comment by michael-bateman** [comment]
Hi @gafetest ,

I am trying multiple methods of figuring out the issue.  You can see it here: https://github.com/michaelbateman-sandbox/projects-website

**Comment by michael-bateman** [comment]
Hello @gafetest ,

I've found a temporary fix for your issue.

The issue was the "GitHub Links" section.

So what I've done, is just completely removed them from the website, for now.  Once I find a fix, that issue will be fixed.

Thanks for finding this
